language: r
r:
  - oldrel
  - release
  - devel

cache: packages

os:
  - linux
  - osx

matrix:
  exclude:
    - r: devel
      os: osx

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
